- name: Remove CoreDNS installer
  ansible.builtin.file:
    path: "/opt/coredns/coredns_{{ coredns_version }}_linux_amd64.tgz"
    state: absent

- name: Restart CoreDNS
  ansible.builtin.systemd_service:
    name: coredns
    state: restarted
    daemon_reload: true
    enabled: true